source 'https://rubygems.org'

#--------------------------------------------------------------------------------------------------
# Core
gem 'rails', '~> 4.2'                     # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'mysql2', '~> 0.4'                    # Fast MySQL gem
gem 'sass-rails', '~> 5.0'                # Use SCSS for stylesheets
gem 'haml', '~> 4.0'                      # Use HAML for views, see http://haml.info
gem 'uglifier', '>= 1.3'                  # Use Uglifier as compressor for JavaScript assets
gem 'validates_timeliness', '~>4.0'       # Date and Time validation
gem 'validates_zipcode', '~> 0.0.8'       # Zipcode validation

gem 'jquery-rails'                        # Use jquery as the JavaScript library
gem 'jbuilder', '~> 2.0'                  # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'sdoc', '~> 0.4', group: :doc         # bundle exec rake doc:rails generates the API under doc/api.

# gem 'unicorn'                             # Use Unicorn as the app server
gem 'thin'                                # Use thin for the web server
gem 'capistrano-rails', group: :development # Use Capistrano for deployment

#--------------------------------------------------------------------------------------------------
# AuthN / AuthZ
gem 'devise', '~> 3.5'                    # Use Devise for authN, see http://devise.plataformatec.com.br

gem 'omniauth', '~> 1.2'                  # Use OmniAuth for authN, see https://github.com/intridea/omniauth
gem 'omniauth-oauth', '~> 1.1'            # Use OmniAuth for OAuth2
gem 'omniauth-oauth2', '~> 1.4'           # Use OmniAuth for OAuth2

# See https://github.com/intridea/omniauth/wiki/List-of-Strategies for strategies
gem 'omniauth-facebook', '~> 3.0'         # Use OmniAuth for Facebook, see https://github.com/mkdynamic/omniauth-facebook
gem 'omniauth-google-oauth2', '~> 0.2'    # Use OmniAuth for Google, see https://github.com/zquestz/omniauth-google-oauth2
gem 'omniauth-linkedin', '~> 0.2'         # Use OmniAuth for LinkedIn, see https://github.com/decioferreira/omniauth-linkedin-oauth2
gem 'omniauth-twitter', '~> 1.2'          # Use OmniAuth for Twitter, see https://github.com/arunagw/omniauth-twitter

gem 'acts-as-taggable-on', '~> 3.5'       # Allows tagging of various objects

# gem 'therubyracer', platforms: :ruby    # See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'bcrypt', '~> 3.1.7'                # Use ActiveModel has_secure_password
# gem 'turbolinks'                        # Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks

group :development, :test do
  gem 'annotate', '~> 2.6'                # Annotate models
  gem 'byebug'                            # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  # gem 'factory_girl_rails', '~> 4.5'      # Use FactoryGirl for seeds and what not
  gem 'rspec', '~> 3.3'                   # Use Rspec for testing, see http://rspec.info/
  gem 'rspec-rails', '~> 3.3'
end

group :development do
  gem 'web-console', '~> 2.0'             # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'spring'                            # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'foreman'                           # Foreman to run dependent processes. Read more: https://github.com/ddollar/foreman
end


gem 'mocha', group: :test
