version: "3"

services:
  app: &app
    build:
      context: .
    depends_on:
      - db
    networks:
      - webnet
    ports:
      - 3000:3000
      - 3035:3035
    tmpfs:
      - /app/tmp
      - /app/log
    volumes:
      - .:/app
    working_dir: /app

  dev: &dev
    <<: *app
    environment:
      RAILS_ENV: development
      RACK_ENV: development
    command: "bash"

  server:
    <<: *dev
    command: "/go/bin/hivemind Procfile"

  test: &test
    <<: *app
    environment:
      RAILS_ENV: test
      RACK_ENV: test

  db: &db
    # See https://store.docker.com/images/mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysql", "--user=root", "--password=root", "--execute='select 1;'"]
      interval: 1s
      timeout: 1s
      retries: 300
    networks:
      - webnet
    volumes:
      - "db-data:/var/lib/mysql"

networks:
  webnet:

volumes:
  db-data:
